/*
	Created by Bernardino Frola - ISISLab - University of Salerno.
	4th Jan 09
*/

#pragma once

#include "CrowdSteer.h"
#include "[PName]_kernel.cuh"

/// Autogenerated namespace
namespace [PName]
{
	/**
		\brief Put here brief the description of the plugIn
		
		Put here the detailed description of the plugIn
	*/
	template <class Super>
	class [PName]PlugIn: public Super, public SimEnginePlugIn
	{
	public:
		// /////////////////////////////////////////////////////
		// Constructor/Descructor

		/// Defautl constructor: provides plugIn installation
		[PName]PlugIn() { SimEnginePlugIn::installPlugIn(); }

		/// Defautl constructor: provides plugIn uninstallation
		~[PName]PlugIn() { SimEnginePlugIn::uninstallPlugIn(); }
		
		const std::string name() { return "[PName]PlugIn"; }	

		/// Dependeciens: none
		const DependenciesList plugInDependencies() 
		{ 
			DependenciesList dependencies;
			[PDependencies]
			return dependencies;	
		}

		// ////////////////////////////////////////////////////
		// Methods
	private:
		/// @override
		void install();
		
		/// @override
		void uninstall();

	public:
		/// @override
		void reset();

		/// @override
		void update(const float elapsedTime);

		// Custom operations
	public:
		// Put here the functionalities
		[PFunctionalitiesDeclaration]

		// ////////////////////////////////////////////////////
		// Fields	
	protected:
		// Put here features
		[PFeaturesDeclaration]
	};
}

using namespace [PName];

// --------------------------------------------------------------
// --------------------------------------------------------------
// --------------------------------------------------------------
// Implementation
template <class Super>
void [PName]PlugIn<Super>::install()
{
	// Put here parameters loading from config file
	// The first letter of ParamType must be capital
	// Example:
	// read_config_param([PName], paramName, ParamType);
	
	[PParamsLoading]

	// Put here the feature allocation. Each feature is a DeviceArrayWrapper object
	// Example:
	// m_AgentHash = new CrowdSteer::DeviceArrayWrapper<uint2>(
	//	community.getDeviceInterface(), 
	//	hBody3DParams.numBodies);

	[PFeaturesAllocation]

	// When you want to transfert params and fields to device
	// use this function:
	[PName]::[PName]_copyFieldsToDevice();
}

// --------------------------------------------------------------

template <class Super>
void [PName]PlugIn<Super>::uninstall()
{
	// Put here memory deallcation
	// Example
	// delete m_AgentHash

	[PFeaturesDeallocation]
}

// --------------------------------------------------------------

template <class Super>
void [PName]PlugIn<Super>::reset()
{
	Super::reset(); // MANDATORY OPERATION
}

// --------------------------------------------------------------

template <class Super>
void [PName]PlugIn<Super>::update(const float elapsedTime)
{
	Super::update(elapsedTime); // MANDATORY OPERATION

	// Insert here the default update operation
}

// --------------------------------------------------------------
// --------------------------------------------------------------

[PFunctionalities]
{
	community.getDeviceInterface()->kernelCall(
		hBody3DParams.numBodies, 
		community.getDeviceInterface()->getHostSimParams().commonBlockDim,
		[PName]_kernelExampleRef(), 
		&Proximity3D_beforeKernelCall, 
		&Proximity3D_afterKernelCall);	
}

// --------------------------------------------------------------